default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: tvapi_development

test:
  <<: *default
  database: tvapi_test

production:
  <<: *default
  database: tvapi_production
