# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08dc320f89c24aa5c9f2dc77152222195e43b80dd0df9541746be2fdd6ed996c6ae6bb57d0574a4d75c7525f3915909f5e30f359fa0e81e772cd268f0313622b

test:
  secret_key_base: 9ab8b2f50e2e837c35ba19feaca528d00fa6419f177bc0f78c6c1ddbabf4a97a5d2322f5e7c0a408e74b4bf45fdd2b8c281ec5e3c60b01a6d2487a1bd22b7011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
